### ISSUE TITLE
Copy edit on Python cheat sheet

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/astro-pi-guide#12]
@AisforAstronaut and I would like to be able to copy edit the Python cheat sheet which is linked to from this resource (https://github.com/raspberrypilearning/astro-pi-guide/blob/master/files/SenseHAT-Cheatsheet.pdf). Can one or other of us have access to the original file please?

**Comment by lawsie** [comment]
I think there are a number of mistakes/out of date bits of code in this cheat sheet. I will test it and let you know. I don't have the original file though, do you have it now?

**Comment by AisforAstronaut** [comment]
I don't seem to. Only the link from the resource...

**Comment by lawsie** [comment]
I've just got a copy from James. I'll check the code for errors, correct them and then make a waffle card for you guys?

**Comment by lawsie** [comment]
Code fixed, waffle issue created, over to you. :)
