### ISSUE TITLE
Copy edit (and design pass?) needed on pixel worksheet

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/astro-pi-guide#13]
@AisforAstronaut and I need to correct a couple of things in the pixel worksheet (https://github.com/raspberrypilearning/astro-pi-guide/blob/master/files/printable-worksheet.pdf). We wondered whether it also needs to go through design again, as some of the images look a little fuzzy, and some of the font sizing seems as if it is inconsistent.

**Comment by samalderhyde** [comment]
This wasn't designed by us, I believe Carrie put this together some time ago.

**Comment by LornaLynch** [comment]
@MissPhilbin Do you happen to have this document so that @AisforAstronaut or I could give it a quick copy edit?

**Comment by MissPhilbin** [comment]
Do either of you use keynote on mac?

**Comment by LornaLynch** [comment]
I can do, @MissPhilbin :)

**Comment by MissPhilbin** [comment]
Great, I'll email over the file.

**Comment by LornaLynch** [comment]
Thank you!

**Comment by lawsie** [comment]
Has this been done @LornaLynch (wondering if I can close the card yet or not?)

**Comment by LornaLynch** [comment]
Sorry @lawsie I haven't had a chance yet: I've been without childcare for a while and I've had to prioritise very strictly.

**Comment by lawsie** [comment]
@LornaLynch Not at all having a "go" - I don't know anything about this card but it shows up on our "resource issues" waffle and it hadn't been updated for quite a while so I thought maybe it had been done but the card had been forgotten about. I was just trying to be tidy! :)

**Comment by LornaLynch** [comment]
I completely understand :) I've just finished a big task which has been rumbling on, so I'd hope I'd be able to get onto this ASAP.

**Comment by LornaLynch** [comment]
I'm just going to start looking at this now.

**Comment by LornaLynch** [comment]
@samaaron I've gone through this with @AisforAstronaut, and we wondered if you'd be able to do a revised version of the handout, with your iD magic applied? 

I can email you with further details, but I've extracted all the text into a Google doc so you can drop it into an iD document: https://docs.google.com/a/codeclub.org.uk/document/d/1Nx_UPNVxXzOdMLR7xBmuTv0Zlzms1vtgAuyeNvjF5Ws/edit?usp=sharing 
The original (corrected) PDF is here: 
[Sense HAT slides.pdf](https://github.com/raspberrypilearning/astro-pi-guide/files/1015361/Sense.HAT.slides.pdf)

**Comment by samaaron** [comment]
@LornaLynch I assume you mean @samalderhyde? :-)

**Comment by LornaLynch** [comment]
Oh, sorry @samaaron! I did mean @samalderhyde: curse that autocomplete...

**Comment by samaaron** [comment]
@LornaLynch - no worries :-)

**Comment by LornaLynch** [comment]
This is all done, and the new worksheet is in place (..files/Sense-HAT-Worksheet-Digital.pdf). I've deleted the old printable worksheet pdf and updated the links, as the new PDF worksheet replaces it.
