### ISSUE TITLE
code fixes for "Reaction Game" in Sense Hat Python cheatsheet

### ISSUE THREAD

**Issue by kurtgraustein** [raspberrypilearning/astro-pi-guide#14]
While working through the [Sense HAT Python cheatsheet](https://www.raspberrypi.org/learning/astro-pi-guide/files/SenseHAT-Cheatsheet.pdf) I found some errors that prevent the game from working.  The `sense.get_accelerometer_raw().values()` call returns a dictionary with index values 'x', 'y' and 'z', but the program sets variables x, y and z by position instead of index values.  When I ran it, the actual value for index 'z' was being assigned to variable y.  The following revised code block works:

```python
    acceleration = sense.get_accelerometer_raw()
    x = round(acceleration['x'], 0)
    y = round(acceleration['y'], 0)
    if y==-1 and angle==180:
        sense.set_pixels(arrow_green)
        score=score+1
    elif y==1 and angle==0:
        sense.set_pixels(arrow_green)
        score=score+1
    elif x==-1 and angle==90:
        sense.set_pixels(arrow_green)
        score=score+1
    elif x==1 and angle==270:
        sense.set_pixels(arrow_green)
        score=score+1
    else:
        sense.set_pixels(arrow_red)
        play=False
```
Note that I had to adjust the if / elif conditions to get this to work properly.

**Comment by lawsie** [comment]
Thanks for reporting this @kurtgraustein - we will look into it soon when we get a moment.

**Comment by lawsie** [comment]
Hi @kurtgraustein 
Thank you for reporting this, you are right that it is not possible to do
```python
x, y, z = sense.get_accelerometer_raw().values()
```

...as values are stored in a dictionary via a hash table, so they will not necessarily be unpacked in the same order. I've edited the file and it is going through copy edit before being updated, so expect to see a new version soon.
