### ISSUE TITLE
Outdated introduction and video

### ISSUE THREAD

**Issue by helenlynn** [raspberrypilearning/astro-pi-guide#18]
The opening copy was written before the Astro Pis arrived on the ISS ("Two specially adapted Raspberry Pis will be travelling [...] The Raspberry Pis will include [...]"). The video was made for the first Astro Pi competition and is no longer the best one to represent the programme. It might be better just to refer people to [https://astro-pi.org/](https://astro-pi.org/) so that this guide doesn't just become outdated again.

**Comment by lawsie** [comment]
As you say @helenlynn this hasn't been updated in a while and we haven't moved it to /learning because we are still working out what format guides like this will take in the future. There is an up to date version of the "Getting started with the Sense HAT" guide which covers all of the hardware bits, and together with the Astro Pi site probably covers all the rules. I think I am right to say that we would be happy to retire this resource, redirect the URL to the Astro Pi site and replace with a combination of the site and the Sense HAT, but of course @davidhoness might have other opinions!

cc @rik-cross

**Comment by lawsie** [comment]
Also see #17 for implications re: Astro Pi video, although this might be able to be mitigated by redirecting the URL to something useful, depending on what's shown in the video.

**Comment by helenlynn** [comment]
I agree with all of this! I should've noted how I came across it, as I've now forgotten - can't find any prominent backlinks though.

**Comment by lawsie** [comment]
Having chatted to the content team, we would like to do the following:

1. Archive the Astro Pi guide resource and redirect visitors to that URL to the Astro Pi website instead.
2. Remove the link to the Astro Pi guide on the Astro Pi website - possibly where you came across it @helenlynn ?

This video #17 has a screencast at the end which shows the use of the old Astro Pi guide resource. The same content is inside the newly updated resource  https://projects.raspberrypi.org/en/projects/astro-pi-flight-case 
The step is "Test the buttons" but at the moment it's not possible to directly link to a step.

3. Update the video with a new screencast showing the up to date resource OR put a comment on the video giving a link to where these commands can now be found. 

I can do action 1, I can request action 2 from the web team but action 3 will need to be @davidhoness and @brian-rpi 

Any problems with this plan?

**Comment by helenlynn** [comment]
Looks good to me.

**Comment by lawsie** [comment]
OK. @davidhoness has removed the link from the Astro Pi website and replaced it. There is already a comment on the video explaining where the information now lives. 

I have requested a redirect from the web team to archive the resource (https://github.com/RaspberryPiFoundation/ups/issues/614) , and I've removed it from the tiles on raspberrypi.org

**Comment by aldreth** [comment]
https://github.com/RaspberryPiFoundation/ups/issues/614 all done :)

**Comment by lawsie** [comment]
Sweet, thanks Edward. Closing this issue!
