### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/astro-pi-guide#3]
Hi @lauraclay & @LornaLynch, hope you are well. I know some of this repo has been through copy, but could the rest be completed so that we can publish it tomorrow? Perhaps you could divide the pages between yourselves to make it easier? It would be super helpful. 

Many thanks!

**Comment by davidhoness** [comment]
Hi folks, I have just updated the [buttons](https://github.com/raspberrypilearning/astro-pi-guide/blob/master/inputs-outputs/buttons.md) part of this resource. Just needs a quick copy edit. Many thanks
