### ISSUE TITLE
Refer to "Sense HAT" not "Astro Pi HAT"

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/astro-pi-guide#4]
I've updated the `hardware.yml` and `hardware.md` files but the worksheets need updating too.

**Comment by MissPhilbin** [comment]
I've just been through the README, board and assemble files to replace "Astro Pi HAT or board" with "Sense HAT" where appropriate. @LornaLynch would you mind casting your eye over the files incase I've missed any?

**Comment by LornaLynch** [comment]
Sure, will do.

**Comment by LornaLynch** [comment]
Just to check: would you like me to change the wording in the Teach resource too (https://www.raspberrypi.org/learning/getting-started-with-astro-pi/)?

**Comment by bennuttall** [comment]
Yes please - see [Issue #6](https://github.com/raspberrypilearning/getting-started-with-astro-pi/issues/6)

**Comment by LornaLynch** [comment]
So, just to be clear: any reference in the resources should be changed, unless it's related to the actual Astro Pi competition, or the board going to the ISS? Should the resource titles be changed too?

**Comment by bennuttall** [comment]
Sorry, we've been all over the place this week deciding what to name things.

So, in short, the hardware board is the Sense HAT; and the competition is Astro Pi.

References to the hardware as "Astro Pi" should be replaced with "Sense HAT", but the Astro Pi mission should be mentioned in context, e.g. the Sense HAT is the hardware created for the Astro Pi mission.

Let's leave the resource names for now.

Thanks

**Comment by bennuttall** [comment]
Further complication: we just changed the software so that you use `from sense_hat import SenseHat` rather than `from astro_pi import AstroPi`. Once the software changes have been completed we'll update the code in the resources too! \o/

**Comment by LornaLynch** [comment]
Thanks! That's a big help: I'll leave the code and the actual resource titles alone for now, and I'll carry on making the other changes. I just wasn't sure where to draw the line before!

**Comment by LornaLynch** [comment]
@bennuttall With regard to the previous URL confusion with the Sense HAT resource, should the resource and URL be changed to something like "Guide to the Sense HAT and the Astro Pi competition"? I don't want to get trigger-happy with the URL again.

**Comment by bennuttall** [comment]
It's a difficult one. This resource is more centred towards the competition. Let's leave it for now and see.

**Comment by LornaLynch** [comment]
OK, will do. I think everything is sorted now.
