### ISSUE TITLE
Update software installation and all code examples from AstroPi to SenseHat

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/astro-pi-guide#5]
- Software installation is now `sense-hat` - see [docs](https://pythonhosted.org/sense-hat/)
- `from astro_pi import AstroPi` becomes `from sense_hat import SenseHat`
- `ap = AstroPi` becomes `sense = SenseHat`
- `ap.` becomes `sense.`

**Comment by bennuttall** [comment]
I'll do this now

**Comment by bennuttall** [comment]
I've done all the text - @jrobinson-uk you just need to replace the cheat sheet PDF

**Comment by jrobinson-uk** [comment]
All done
