### ISSUE TITLE
Screws & spacers not always included

### ISSUE THREAD

**Issue by helenlynn** [raspberrypilearning/astro-pi-guide#6]
`assemble.md` says the Sense HAT comes with screws, spacers and GPIO extension header, but not all sellers are including screws and spacers, though my impression is that the header is included by Farnell and RS (and presumably therefore resellers).

This is the first time I've opened an issue - please tell me if I'm doing stuff wrong!

**Comment by bennuttall** [comment]
Thanks @helenlynn - very useful issue, well opened. 10/10. Would recommend. A++.

This resource was written for the Astro Pi competition, and all entrants got sent a Sense HAT with all the bits. I didn't know the HAT was being sold without them.

I'm away for a few days - can someone update the assembly instructions accordingly?

**Comment by LizUpton** [comment]
The HATs from the Swag store come with bundled spacers and screws. Nothing's happening yet with the other retailers, but they're looking into it; I'd recommend we hold off on amending until we've got confirmation on what's happening.

**Comment by helenlynn** [comment]
Ah, thanks @LizUpton. Today's blog post and [element14's asterisked note] (http://www.element14.com/community/docs/DOC-78155?ICID=hp-pisensehat-ban) strongly suggest they're not automatically included but I'd been trying and failing to figure out exactly what the distributors were doing. I'll leave it for now. Thanks for your supportive words @bennuttall.

**Comment by LizUpton** [comment]
Yeah - the asterisked note is there because we asked them to put it there for the time being. Awesome issue. 100% great. V good. A+.

**Comment by LornaLynch** [comment]
Popping up to say that can edit the information in the future if need be. Top notch issue-opening, @helenlynn!

**Comment by bennuttall** [comment]
I've also noticed the Sense HATs include the fixed header so that part isn't separate as it is in the diagram.

@samalderhyde can you change the graphic so it's just the HAT being attached to the Pi. No screws or stands, no additional pin header?

**Comment by samalderhyde** [comment]
Yeah sure

**Comment by lawsie** [comment]
Closing because I think this issue has been done.
